Add "amount" field to "wallet inscriptions" output.
ordinals/ord pull request #1928
Opened 2023-03-13 16:34 UTC by gmart7t2

Allow people to check the postage on each of their inscriptions.

2023-03-16 11:45 UTC, rot13maxi commented
this is always going to be 10000 until we have an option to change the output postage amount, or am I missing something?

2023-04-13 18:05 UTC, raphjaph commented
When sending around inscriptions the postage will decrease over time. It will only be replenished if it would go below the dust limit. So this change makes sense.

2023-04-19 19:00 UTC, raphjaph requested changes
Reviewing with Casey. This is missing a few things that he will address in his review.

2023-04-19 19:03 UTC, casey requested changes
Nice! This is a good addition.

This requires a test! We should have an integration test that the returned `postage` field is correct. Add one in `tests/wallet/inscriptions.rs`.

2023-04-19 19:03 UTC, casey commented on src/subcommand/wallet/inscriptions.rs
> +  pub amount: u64,
I think `postage` is clearer than `amount` here:

```suggestion
  pub postage: u64,
```

2023-04-19 19:03 UTC, casey commented on src/subcommand/wallet/inscriptions.rs
> +  pub amount: u64,
Struct fields should be sorted.

2023-04-19 19:03 UTC, casey commented on src/subcommand/wallet/inscriptions.rs
> +        amount: unspent_outputs.get(&location.outpoint).unwrap().to_sat(),
Refactor to use `if let …` and avoid the unwrap, like so:

```
    if let Some(output) = unspent_outputs.get(&location.outpoint) {
      output.push(Output {
        location,
        inscription,
        explorer: format!("{explorer}{inscription}"),
        amount: output.to_sat(),
```

2023-07-24 20:44 UTC, raphjaph approved these changes

2023-07-24 20:48 UTC, merged