fix: add retry to fetcher
ordinals/ord pull request #2297
Opened 2023-07-22 06:22 UTC by victorkirov

Resolves: #2248 

Sometimes the transaction fetcher receives a non-json response from bitcoin core, resulting in a parsing error. It seems to happen due to load on the node. This is problematic because it will completely fail a batch of processed blocks. With the batch size set top 5000, if it fails a few thousand blocks in, it will be a lot of work to start over again.

This adds a retry which tries to fetch transactions a total of 3 times with a short sleep between tries.

2023-07-22 06:32 UTC, victorkirov commented
If this should go in, maybe it should be a back off retry and maybe a few more times (5 total maybe?). Let me know.

2023-07-22 07:24 UTC, nick07002 approved these changes
Great stuff! This is going to help a lot of people overcome their indexing hiccups

2023-07-22 07:24 UTC, nick07002 commented on src/index/fetcher.rs
> +          tokio::time::sleep(tokio::time::Duration::from_millis(100)).await;
The wait time of 100ms seems small.
maybe could use backoff retry.

2023-07-22 08:18 UTC, victorkirov commented
Great. I'll fix up the logging and make it a back off retry a bit later today when I'm at my pc.

2023-07-22 21:15 UTC, raphjaph requested changes
Thanks, the logic looks good so far! Just some minor tweak needed.

2023-07-22 21:15 UTC, raphjaph commented on src/index/fetcher.rs
> +              "Failed to fetch raw transactions after 5 retries. Error: {}",
```suggestion
              "failed to fetch raw transactions after 5 retries: {}",
```
We're not very consistent with not capitalizing error message ourselves but I want to try to do that. So if you could make all the error messages lowercase that would be great. Also I don't think we need the "Error:" just colon or semicolon and then the "{}". Thanks!

2023-07-22 21:15 UTC, raphjaph commented on src/index/fetcher.rs
> +          "Failed to parse JSON-RPC response: {e}. Response: {response}",
same as above

2023-07-22 21:15 UTC, raphjaph commented on src/index/fetcher.rs
> +            "Failed to fetch raw transactions, retrying. Error: {}",
same as above

2023-07-22 21:39 UTC, raphjaph commented on src/index/fetcher.rs
> +          let sleep_time = tokio::time::Duration::from_millis(100 * u64::pow(tries, 2));
```suggestion
          let sleep_time = tokio::time::Duration::from_millis(100 * u64::pow(2, retries));
```
I think we want this for exponential backoff.

2023-07-23 05:22 UTC, victorkirov commented on src/index/fetcher.rs
> +          tries += 1;
Ah, good catch 😄

2023-07-23 05:27 UTC, victorkirov commented
Thanks for the review @raphjaph. I think it should all be sorted 🙂

2023-07-23 12:28 UTC, raphjaph approved these changes

2023-07-23 12:28 UTC, merged