Batch reinscribe
ordinals/ord pull request #2749
Opened 2023-11-25 16:37 UTC by raphjaph

2023-11-26 00:29 UTC, elocremarc commented
Will this create a new cursed type? Do we need to consider this in the jubilee?

2023-11-26 15:05 UTC, raphjaph commented
Shouldn't require a new curse. This isn't a new protocol feature just a new wallet feature.

2023-11-27 23:08 UTC, casey requested changes

2023-11-27 23:08 UTC, casey commented on src/subcommand/wallet/inscribe.rs
> +        }
```suggestion
```

2023-11-27 23:08 UTC, casey commented on src/subcommand/wallet/inscribe/batch.rs
> +  Reinscribe,
Maybe we should call this `SharedSat` or `SameSat`?

2023-11-28 20:02 UTC, casey commented on batch.yaml
> +# - `same-sat`: place inscriptions on the same sat
```suggestion
# - `separate-outputs`: inscribe on separate postage-sized outputs
# - `shared-output`: inscribe on a single output separated by postage
# - `same-sat`: inscribe on the same sat
```

2023-11-28 20:08 UTC, casey commented on src/subcommand/wallet/inscribe/batch.rs
>        Mode::SharedOutput => vec![get_change_address(client, chain)?],
```suggestion
      Mode::SameSat | Mode::SharedOutput => vec![get_change_address(client, chain)?],
```

2023-11-28 20:09 UTC, casey commented on src/subcommand/wallet/inscribe/batch.rs
>            Mode::SharedOutput => total_postage.to_sat(),
```suggestion
          Mode::SameSat | Mode::SeparateOutputs => self.postage.to_sat(),
          Mode::SharedOutput => total_postage.to_sat(),
```

2023-11-28 20:09 UTC, casey commented on src/subcommand/wallet/inscribe/batch.rs
> +        "invariant: reinscribe has only one destination"
```suggestion
        "invariant: same sat can only inscribe to one destination"
```

2023-11-28 20:30 UTC, casey approved these changes

2023-11-28 20:33 UTC, merged