Wallet talks to index over http
ordinals/ord pull request #2929
Opened 2023-12-31 15:14 UTC by raphjaph

Starts work on converting the wallet to talk to the index over JSON endpoints on the server. This way server and wallet can run concurrently 

#2736

2024-01-11 22:21 UTC, raphjaph commented
@casey This is ready for a review. It's kinda gnarly but there was no way to break it up into smaller pieces. Lord have mercy on thy soul.

2024-01-12 21:03 UTC, casey requested changes
Let's also modularize, putting Wallet into its own module, `src/wallet.rs`, as well as not spinning up a server when running a wallet runs, requiring that an existing server be running.

2024-01-22 22:11 UTC, raphjaph commented
@casey Ready to review.

The integration tests now run really fast. Made our testing harness start threads instead of child processes. Also I remove the `ord preview` command since I think nobody uses that.

2024-01-23 00:17 UTC, casey approved these changes

2024-01-23 00:22 UTC, merged