Add router Runes balance and format Tx response to JSON
ordinals/ord pull request #2978
Opened 2024-01-07 06:17 UTC by lugondev

- Formatting response `/tx/{tx_id}` into JSON
- Add router `/runes/balance` to fetch all runes balance

2024-01-07 06:29 UTC, lugondev commented
@casey @raphjaph I want to bring more the functions from commands to server routes to make it easier for UI access and development.

Following: https://github.com/ordinals/ord/issues/2936

2024-01-07 07:14 UTC, alexluffy commented
Hi mr @lugondev . 
I'm Frontend developer .
"How can I assist you? I can help you design and code a UI/UX page for a DApp. Once you complete the API, I can integrate it into the project. What do you think?"

2024-01-07 07:52 UTC, doshidev99 commented
Hi @lugondev gon

I highly value your PR work. I have connected with you, and we can possibly collaborate together
( Web3 dev ) 
Thank

2024-01-09 01:50 UTC, raphjaph requested changes
Looks good so far! 

Could you add tests for both endpoints in `tests/json_api.rs`?

2024-01-09 01:50 UTC, raphjaph commented on src/subcommand/server.rs
> +    Extension(_): Extension<Arc<ServerConfig>>,
```suggestion
```

2024-01-09 02:55 UTC, lugondev commented
Ok, I will do it

2024-01-28 07:44 UTC, lugondev commented
hi @raphjaph, it's been a long time. I have just added tests for the router, all tests passed in my local but had a failure tests in CI. 
give me any feedback
thanks!

2024-01-29 03:09 UTC, raphjaph requested changes
Just some minor things.

I'm also thinking we should probably also add an HTML page for this. If you have a good idea how to display this let me know. Probably some `<dl>`/`<dt>` list.

2024-01-29 03:09 UTC, raphjaph commented on src/subcommand/server.rs
> +      .into_response()
We need to surround this in `task::block_in_place`

2024-01-29 03:09 UTC, raphjaph commented on src/subcommand/server.rs
> +    Ok(Json(index.get_rune_balance_map()?).into_response())
```suggestion
        task::block_in_place(|| Ok(Json(index.get_rune_balance_map()?).into_response()))
```

2024-01-29 05:08 UTC, lugondev commented
> Just some minor things.
> 
> I'm also thinking we should probably also add an HTML page for this. If you have a good idea how to display this let me know. Probably some `<dl>`/`<dt>` list.

yeah, will I do it in next pull request?

2024-01-29 05:10 UTC, lugondev commented
> > Just some minor things.
> > I'm also thinking we should probably also add an HTML page for this. If you have a good idea how to display this let me know. Probably some `<dl>`/`<dt>` list.
> 
> yeah, will I do it in next pull request?

I would like to use this endpoint for my product with the official repo `ord`. Thank you for understanding.

2024-01-30 10:52 UTC, lugondev commented
@raphjaph help me check this pull request

2024-01-31 04:10 UTC, raphjaph approved these changes
LGTM!

Just fixed some small things here and there

2024-01-31 04:55 UTC, lugondev commented
> LGTM!
> 
> Just fixed some small things here and there

thanks you so much

2024-01-31 05:32 UTC, casey approved these changes
Looks good @lugondev, amazing work!

2024-01-31 05:49 UTC, merged