add prompt for seed when restoring wallet
ordinals/ord pull request #3023
Opened 2024-01-16 02:17 UTC by mj10021

Fixes issue #2990 by allowing a seed to be entered to stdin when restoring a wallet.  I'm not sure if I got the type coercion/checking exactly right here, so would appreciate any feedback/help.  Thanks!

2024-01-23 21:54 UTC, raphjaph requested changes
This is good start! Definitely add a an integration test somewhere in `tests/wallet`. If you need help with that let me know.

2024-01-23 21:54 UTC, raphjaph commented on src/subcommand/wallet/restore.rs
> +use std::io;
combine these two
```rust
use {
  super::*,
  std::io,
};
```

2024-01-23 21:54 UTC, raphjaph commented on src/subcommand/wallet/restore.rs
> +        assert_eq!(input.len(), 64);
not sure if we need this the `Mnemonic` might already perform these checks.

2024-01-26 02:50 UTC, raphjaph commented
@mj10021 Have a look at #3048. I read the descriptor from stdin and also have some tests in there that you can use as a template.

2024-01-26 12:52 UTC, mj10021 commented
thanks :) i'm away this weekend but should have done early next week

2024-02-01 21:48 UTC, mj10021 commented
hey @raphjaph , just to clarify, is the stdin meant to accept a descriptor or a mnemonic?

2024-02-02 14:54 UTC, mj10021 commented
> hey @raphjaph , just to clarify, is the stdin meant to accept a descriptor or a mnemonic?

Oh I see, the --descriptor flag lets you enter a descriptor through stdin without the mnemonic

2024-02-02 17:34 UTC, mj10021 commented
Ok, sorry, I actually do need some clarification. I see that now there is an option to restore from stdin and tests have already been made for that. Is this PR now redundant? Or is the option to load a mnemonic from stdin in addition to the descriptor flag also wanted? Thanks!

2024-02-02 21:06 UTC, raphjaph commented
> Ok, sorry, I actually do need some clarification. I see that now there is an option to restore from stdin and tests have already been made for that. Is this PR now redundant? Or is the option to load a mnemonic from stdin in addition to the descriptor flag also wanted? Thanks!

Yes we want to load the mnemonic from stdin only as well. And def also add a separate test for that

2024-02-03 14:11 UTC, mj10021 commented
> > Ok, sorry, I actually do need some clarification. I see that now there is an option to restore from stdin and tests have already been made for that. Is this PR now redundant? Or is the option to load a mnemonic from stdin in addition to the descriptor flag also wanted? Thanks!
> 
> Yes we want to load the mnemonic from stdin only as well. And def also add a separate test for that. Let me know when this is ready for review.

Ok got it thanks.  I'm not able to run the tests atm but I think this should be right?

2024-02-12 04:11 UTC, raphjaph commented
Tests aren't passing yet. Install `just` and run `just ci` to run all our tests.

2024-02-15 00:37 UTC, mj10021 commented
> Tests aren't passing yet. Install `just` and run `just ci` to run all our tests.

Got it, thanks.  Should be good now.

2024-02-16 18:18 UTC, raphjaph approved these changes
LGTM

2024-02-16 18:22 UTC, merged