chore: modify description on inscription sat
ordinals/ord pull request #3114
Opened 2024-02-13 05:56 UTC by zhiqiangxu

The inscription is not necessarily on the first sat if there's a pointer tag specified.

2024-02-13 19:10 UTC, raphjaph requested changes
Looks good!

Minor nit

2024-02-13 19:10 UTC, raphjaph commented on docs/src/inscriptions.md
> +tag specified. This sat can then be tracked using the familiar rules of ordinal
```suggestion
and the inscription is made on the first sat of its input if it has no pointer
field. This sat can then be tracked using the familiar rules of ordinal 
```

2024-02-13 23:33 UTC, raphjaph commented on docs/src/inscriptions.md
> -| 4     | 1                 | i6         |
I think we just want to stick to the old versoin.

2024-02-15 20:48 UTC, JohnKraken approved these changes
Better this way...

2024-02-27 16:45 UTC, raphjaph approved these changes

2024-02-27 16:49 UTC, merged