Build wallet state asynchronously
ordinals/ord pull request #3142
Opened 2024-02-18 20:47 UTC by raphjaph

Fixes #3061

2024-02-19 15:24 UTC, gmart7t2 commented
> @devords, @gmart7t2 Could you check if this makes things faster on your end?

It's 11x faster than the master branch, but 11x slower than 0.15.0:

```
$ time echo $(ordr2-new balance) # origin/master
{ "cardinal": 3003000, "ordinal": 0, "total": 3003000 }

0m8.859s  0m9.030s  0m8.832s

$ time echo $(ordr2-new balance) # make-it-fast
{ "cardinal": 3003000, "ordinal": 0, "total": 3003000 }

0m0.676s  0m0.680s  0m0.714s

$ time echo $(ordr2 balance) # 0.15.0
{ "cardinal": 3003000, "ordinal": 0, "total": 3003000 }

0m0.052s  0m0.062s  0m0.072s
```

Trying with a bigger wallet, with 44 unspent outputs in it, and timing "wallet balance":

origin/master: 150s
make-it-fast: 5.3s
0.15.0: 0.15s

So make-it-fast is much faster than origin/master but much slower than 0.15.0.

2024-02-20 01:56 UTC, raphjaph commented
@gmart7t2 Thanks for testing this, very helpful numbers!

I wasn't using async properly but now I am. Could you check if it is faster now?

2024-02-21 02:59 UTC, casey requested changes
BACK TO THE DRAWING BOARD

2024-02-21 03:22 UTC, casey approved these changes
LGTM

2024-02-21 03:27 UTC, merged