Extend events channel to Runes
ordinals/ord pull request #3219
Opened 2024-03-05 16:08 UTC by felipelincoln

Extending the work done in PR #3137  to enable rune events.

2024-03-05 16:09 UTC, felipelincoln commented on src/index/event.rs
> +  },
The events fields are TBD

2024-04-12 19:44 UTC, raphjaph requested changes
Good PR!

Sorry for getting to this so late. Would you mind merging in the latest changes and fixing the conflicts? Then I can have a final look

2024-04-12 19:44 UTC, raphjaph commented on src/index/event.rs
> +  RuneClaimed {
```suggestion
  RuneMinted {
```

2024-04-13 17:13 UTC, kevinfaveri commented
gm. hey @raphjaph in case @felipelincoln can we give a prio to adjusting this PR and merging before halving?

Almost everyone with custom infra relies on having those events or forking and adding stuff to Ord API....
Also makes me think, should this be scoped when you guys change Ord? And another question: maybe we think about a headless ord/ord version? That you can plug any DB rather than redb?

2024-04-13 22:17 UTC, raphjaph commented
Ok, I'll try to fix this up

2024-04-14 00:13 UTC, raphjaph commented
Fixed it up. @casey, @felipelincoln, @kevinfaveri this is ready for review

2024-04-14 00:55 UTC, casey approved these changes
LGTM

2024-04-14 01:11 UTC, raphjaph approved these changes

2024-04-14 01:11 UTC, merged