Add wallet database
ordinals/ord pull request #3374
Opened 2024-03-26 03:49 UTC by raphjaph

2024-03-29 01:22 UTC, rot13maxi commented on src/subcommand/wallet.rs
> +  Resume,
🎉

2024-03-31 02:14 UTC, casey requested changes
SO CLOSE

2024-03-31 02:14 UTC, casey commented on src/wallet.rs
> +    commit_tx: Transaction,
Maybe just `commit` and `reveal`?

2024-03-31 02:14 UTC, casey commented on src/wallet.rs
> +        return Err(anyhow!("cancelled"));
I think this shouldn't be an error.

2024-03-31 02:14 UTC, casey commented on src/wallet.rs
> +    self.store(rune, &commit_tx, &reveal_tx, output.clone())?;
Maybe like `save_etching`?

2024-03-31 02:14 UTC, casey commented on src/wallet.rs
> +    self.clear(rune)?;
Maybe `clear_etching`?

2024-03-31 02:14 UTC, casey commented on src/wallet.rs
> +    let repair_callback = move |progress: &mut RepairSession| {
Let's deduplicate this

2024-03-31 02:14 UTC, casey commented on src/wallet.rs
> +          statistics.insert(&Statistic::Schema.key(), &SCHEMA_VERSION)?;
```suggestion
          tx.open_table(STATISTICS)?.insert(&Statistic::Schema.key(), &SCHEMA_VERSION)?;
```

2024-03-31 02:14 UTC, casey commented on src/wallet.rs
> +      Err(error) => bail!("failed to open index: {error}"),
```suggestion
      Err(error) => bail!("failed to open wallet database: {error}"),
```

2024-03-31 02:14 UTC, casey commented on src/wallet.rs
> +  fn begin_read(&self) -> Result<ReadTransaction> {
Let's remove this one

2024-03-31 02:14 UTC, casey commented on src/wallet.rs
> +  fn begin_write(&self) -> Result<WriteTransaction> {
Let's nuke this and not bother setting the durability.

2024-03-31 02:14 UTC, casey commented on src/wallet.rs
> +  pub(crate) fn retrieve(&self, rune: Rune) -> Result<Option<ResumeEntry>> {
```suggestion
  pub(crate) fn load_etching(&self, rune: Rune) -> Result<Option<ResumeEntry>> {
```

2024-03-31 02:14 UTC, casey commented on src/wallet.rs
> +define_table! { RUNE_TO_INFO, u128, ResumeEntryValue }
Maybe `RUNE_TO_ETCHING`?

2024-03-31 02:14 UTC, casey commented on src/wallet.rs
> +  pub(crate) fn pending(&self) -> Result<Vec<(Rune, ResumeEntry)>> {
```suggestion
  pub(crate) fn pending_etchings(&self) -> Result<Vec<(Rune, ResumeEntry)>> {
```

2024-03-31 02:14 UTC, casey commented on src/wallet.rs
> +  pub(crate) fn clear(&self, rune: &Rune) -> Result {
```suggestion
  pub(crate) fn clear_etching(&self, rune: Rune) -> Result {
```

2024-03-31 02:14 UTC, casey commented on src/wallet/entry.rs
> +pub struct ResumeEntry {
```suggestion
pub struct EtchingEntry {
```

2024-03-31 02:14 UTC, casey commented on src/wallet/entry.rs
> +      output: serde_json::from_str(std::str::from_utf8(&output).unwrap()).unwrap(),
```suggestion
      output: serde_json::from_slice(&output)).unwrap(),
```

2024-03-31 02:14 UTC, casey commented on tests/lib.rs
> +  assert_regex_match!(buffer, "Waiting for rune commitment .* to mature…\n");
Maybe check for the txid, like with `[[:xdigit]]{???}`

2024-03-31 20:09 UTC, casey approved these changes
LGTM

2024-03-31 20:35 UTC, merged

2024-04-05 02:13 UTC, Sidey123 commented
Dode the runes wallet down?

2024-04-06 13:03 UTC, Frank-Allen commented
What kind of wallet do you use for Rune?