Add Postage Argument on Mint Command
ordinals/ord pull request #3482
Opened 2024-04-08 21:03 UTC by ynohtna92

Implements the postage argument for the wallet mint subcommand.

2024-04-08 22:21 UTC, raphjaph requested changes
Thanks for the PR! 

Left some comments

2024-04-08 22:21 UTC, raphjaph commented on src/subcommand/wallet/mint.rs
> +    help = "Amount of postage to include in the inscription. Default `10000sat`."
This postage is for the mint of a rune, so no inscription inside. 

```suggestion
    help = "Amount of postage to include in the minted rune output. Default `10000sat`."
```

2024-04-08 22:21 UTC, raphjaph commented on tests/wallet/mint.rs
> +  assert_eq!(balance.runic.unwrap(), 1000_u64);
I don't think you need the `_u64`

2024-04-08 22:21 UTC, raphjaph commented on tests/wallet/mint.rs
> +    "--chain regtest --index-runes wallet mint --fee-rate 1 --rune {} --postage 1000sat",
maybe use 2222sat so it's visually different from the default

2024-04-08 22:21 UTC, raphjaph commented on tests/wallet/mint.rs
> +  assert_eq!(balance.runic.unwrap(), 20000_u64);
```suggestion
  assert_eq!(balance.runic.unwrap(), 20000);
```

2024-04-08 22:21 UTC, raphjaph commented on tests/wallet/mint.rs
> +  assert_eq!(balance.runic.unwrap(), 10000_u64);
```suggestion
  assert_eq!(balance.runic.unwrap(), 10000);
```

2024-04-08 22:21 UTC, raphjaph commented on src/subcommand/wallet/mint.rs
> +    let postage = self.postage.unwrap_or(TARGET_POSTAGE);
If the postage is beneath the dust limit it should return an errors. Something like this:

```
ensure!(
  destination.script_pubkey().dust_limit < postage,
  "postage below dust limit"
);
```

2024-04-09 21:04 UTC, ynohtna92 commented
Thanks for reviewing @raphjaph. I have made all those changes as requested and added a new test for the dust limit.

2024-04-11 02:55 UTC, raphjaph approved these changes
LGTM, great PR!

Just fixed some small things

2024-04-11 03:24 UTC, merged