Add test Rune cannot be minted less than limit amount
ordinals/ord pull request #3556
Opened 2024-04-16 06:37 UTC by lugondev

```rust
pub fn supply(&self) -> u128 {
    self.premine
      + self.mints
        * self
          .terms
          .and_then(|terms| terms.amount)
          .unwrap_or_default()
  }
  ``` 
Added a test case to validate the supply calculation logic.

2024-04-17 19:09 UTC, raphjaph requested changes

2024-04-17 19:09 UTC, raphjaph commented on src/runes.rs
> +            output: 0,
Could you make it a two output transaction? That would make this a better test.

2024-04-17 19:31 UTC, lugondev commented on src/runes.rs
> +        Runestone {
is it right?

2024-04-17 19:31 UTC, lugondev commented on src/runes.rs
> +        Runestone {
@raphjaph  thanks

2024-04-19 19:51 UTC, raphjaph approved these changes

2024-04-19 19:51 UTC, merged