Revert runes balances json
ordinals/ord pull request #3571
Opened 2024-04-17 07:36 UTC by lugondev

2024-04-17 20:19 UTC, raphjaph requested changes

2024-04-17 20:19 UTC, raphjaph commented on src/subcommand/server.rs
> +  async fn runes_balances(Extension(index): Extension<Arc<Index>>) -> ServerResult {
It should have the AcceptJson extension in the function arguments, so that it can be disabled with `--disable-json` flag.

2024-04-17 20:20 UTC, raphjaph commented on src/subcommand/server.rs
> +  async fn runes_balances(Extension(index): Extension<Arc<Index>>) -> ServerResult {
And also it should return a 404 if the client does not set the JSON application header

2024-04-18 05:07 UTC, lugondev commented
@raphjaph done with testcase

2024-04-18 22:52 UTC, casey approved these changes
LGTM

2024-04-18 22:56 UTC, raphjaph approved these changes
LGTM

2024-04-18 23:04 UTC, merged