Allow mint submissions as start block is pending
ordinals/ord pull request #3645
Opened 2024-04-21 19:32 UTC by coinspiracynut

Current implementation only allows mint submissions after the start block is confirmed meaning ord users can not attempt to compete in that block. This implementation allows for submissions at start - 1, which is a good solution for most users. However, a flag to ignore these checks for power users might be a more composable solution.

2024-04-21 19:50 UTC, 0xcruci commented
Referencing this issue for more context https://github.com/ordinals/ord/issues/3643

2024-04-22 03:07 UTC, gmart7t2 commented
Isn't the end check similarly off by one?

If the minting ends at block 80 and block 79 is the current block, new mints won't be accepted in block 80 so don't let people mint after block 79 has been mined

2024-04-22 16:40 UTC, utxo-detective commented
`if height < (start - 1) {` can be simplified to `if height <= start {`

2024-04-22 17:30 UTC, benbuschmann commented
> Isn't the end check similarly off by one?
> 
> If the minting ends at block 80 and block 79 is the current block, new mints won't be accepted in block 80 so don't let people mint after block 79 has been mined

yes

2024-04-22 18:48 UTC, raphjaph requested changes
The projection into the next block should be done on a higher level.

2024-04-22 23:48 UTC, casey commented
Fixed in #3659.

2024-04-22 23:48 UTC, closed without merging

2024-04-23 00:32 UTC, 0xcruci commented
Thanks @casey!