Add --commitment flag to enable resuming a specific etching
ordinals/ord pull request #3679
Opened 2024-04-24 18:34 UTC by ldiego08

Adds a new `--commitment <commitment-id>` flag to allow resuming a specific pending etching by its commitment ID. This is useful in automated scenarios (if anyone else is into that kind of stuff) where you'd like to etch something, suspend (perhaps via `--no-wait` from #3526), do something else, and then resume after the 6 confirmations.

2024-05-06 09:29 UTC, raphjaph requested changes
This is good feature.

We should probably resume it by rune name. Another feature that would improve this would be a command to list all pending etchings, so it is easier to know what can be resumed. Probably best to do another PR for that.

2024-05-06 09:29 UTC, raphjaph commented on src/subcommand/wallet/resume.rs
> +
```suggestion
```

2024-05-06 09:29 UTC, raphjaph commented on src/subcommand/wallet/resume.rs
> +  pub(crate) commitment: Option<String>,
```suggestion
  pub(crate) rune: Option<SpacedRune>,
```

2024-05-06 09:29 UTC, raphjaph commented on src/subcommand/wallet/resume.rs
> +      if let Some(commitment) = commitment {
```suggestion
      if let Some(rune) = self.rune {
```

2024-05-06 22:14 UTC, ldiego08 commented
> This is good feature.
> 
> We should probably resume it by rune name. Another feature that would improve this would be a command to list all pending etchings, so it is easier to know what can be resumed. Probably best to do another PR for that.

Thanks for the feedback, @raphjaph - I'll get these changes in and create a separate PR for listing pending etchings.

2024-05-06 22:33 UTC, ldiego08 commented
Thanks for the feedback, @raphjaph! Requested changes have been applied. Will add the command to show pending etchings on a separate PR.

2024-05-07 11:49 UTC, raphjaph requested changes

2024-05-07 11:49 UTC, raphjaph commented on src/subcommand/wallet/resume.rs
> +          .find(|(rune, _)| *rune == spaced_rune.rune);
```suggestion
          .load_etching(spaced_rune.rune)?;
         
```

2024-05-07 11:49 UTC, raphjaph commented on src/subcommand/wallet/resume.rs
> +      if let Some(spaced_rune) = spaced_rune {
```suggestion
     let pending_etchings = if let Some(spaced_rune) = spaced_rune {
```

2024-05-07 11:49 UTC, raphjaph commented on src/subcommand/wallet/resume.rs
> +      }
```suggestion
        vec![pending_etching.unwrap()]
      } else {
        wallet.pending_etchings()?
      };
```

2024-05-07 11:49 UTC, raphjaph commented on src/subcommand/wallet/resume.rs
> +  #[arg(long, value_name = "PENDING•RUNE", help = "Rune to resume (spaced).")]
```suggestion
  #[arg(long, help = "Rune to resume.")]
```

2024-05-08 10:31 UTC, raphjaph requested changes
Almost there! Still needs an integration test. Have a look at `tests/wallet/resume.rs`. For reasons this can only be tested on Mac and Linux. What system are you on?

2024-05-12 20:51 UTC, ldiego08 commented
> Almost there! Still needs an integration test. Have a look at `tests/wallet/resume.rs`. For reasons this can only be tested on Mac and Linux. What system are you on?

@raphjaph took me a while to get around to adding these tests, but here they are! Hope it's looking good. I'm on a Mac, btw.

2024-05-17 15:27 UTC, raphjaph approved these changes
Great, LGTM!

2024-05-17 15:35 UTC, merged