Add `ord wallet runics` command
ordinals/ord pull request #3734
Opened 2024-05-08 04:13 UTC by ldiego08

Add a new `ord wallet runic` command showing runic unspent outputs and balances. Solves #3729.

2024-05-08 04:17 UTC, ldiego08 commented on src/subcommand/wallet/runics.rs
@raphjaph, does something like this satisfy #3734? It's pretty scrappy code - more interested in functionality atm. I'll polish it if green-lighted.

2024-05-08 10:09 UTC, raphjaph requested changes
Good start, you have the green light. Don't forget to also add an integration test :)

2024-05-08 10:09 UTC, raphjaph commented on src/subcommand/wallet/runics.rs
> +  pub amount: u64,
```suggestion
```

I know I said to add this but after thinking about it I think we should just show the runes balance and not the btc amount.

2024-05-08 10:09 UTC, raphjaph commented on src/subcommand/wallet/runics.rs
> +  pub rune_balance: u128,
```suggestion
  pub runes: BTreeMap<SpacedRune, Decimal>,
```
In theory an output can contain multiple runes, so let's make this a map. Have a look at `src/subcommand/wallet/balance.rs` for how to create this struct.

2024-05-17 14:30 UTC, raphjaph approved these changes
LGTM

2024-05-17 14:39 UTC, merged