Added parents recursive endpoint
ordinals/ord pull request #3749
Opened 2024-05-13 20:37 UTC by phorkish

Added `/r/parents/<INSCRIPTION_ID>` and `/r/parents/<INSCRIPTION_ID>/<PAGE>` endpoints. This should take care of https://github.com/ordinals/ord/issues/3309.

2024-05-18 02:10 UTC, elocremarc commented
@gmart7t2  would it be worth making this endpoint like your doing with the new children endpoint returning `Vec<InscriptionRecursive>` instead of `Vec<Ids>`? https://github.com/ordinals/ord/pull/3761

2024-05-20 20:10 UTC, raphjaph requested changes

2024-05-20 20:10 UTC, raphjaph commented on src/api.rs
> +
On second thought let's just reuse the Inscriptions struct from above

2024-05-20 20:10 UTC, raphjaph commented on src/subcommand/server.rs
> +      Ok(Json(api::Parents { ids, more, page }).into_response())
```suggestion
      Ok(Json(api::Inscriptions { ids, more, page }).into_response())
```

2024-05-20 20:55 UTC, phorkish commented
@raphjaph I've made the change you requested.

2024-05-22 21:51 UTC, raphjaph approved these changes
LGTM

2024-05-22 22:05 UTC, merged