Add delegate value to inscription endpoint
ordinals/ord pull request #3751
Opened 2024-05-14 01:39 UTC by phorkish

Add the delegate ID to the `/inscription/[id]` endpoint. If there is no delegate then the response doesn't include that field.

2024-05-18 01:54 UTC, elocremarc commented
@gmart7t2 This PR is attempting the same thing as yours gonna link these together. 
https://github.com/ordinals/ord/pull/3761

2024-05-22 22:25 UTC, raphjaph requested changes
LGTM, just a small change

2024-05-22 22:25 UTC, raphjaph commented on src/api.rs
> +  #[serde(skip_serializing_if = "Option::is_none")]
```suggestion
```
This is a good idea but in order to stay consistent with the other Option fields we should remove it

2024-05-23 12:29 UTC, gmart7t2 commented
@phorkish That "this branch is out-of-date with the base branch" means that your PR no longer merges cleanly to the upstream repo because something incompatible was merged. You need to merge your change to the master branch and push the change to your branch. 

It's kind of annoying to have to keep doing that, but someone needs to do it.

2024-05-24 11:17 UTC, raphjaph commented
> @phorkish That "this branch is out-of-date with the base branch" means that your PR no longer merges cleanly to the upstream repo because something incompatible was merged. You need to merge your change to the master branch and push the change to your branch. 
> 
> It's kind of annoying to have to keep doing that, but someone needs to do it.

There's a feature on GitHub which auto updates branches if they can be merged cleanly. I'll try to find it and activate

2024-05-24 11:26 UTC, raphjaph commented
#3784

2024-05-24 11:32 UTC, raphjaph requested changes
Sorry, forgot to add the we should add this field to to docs. Could you add the `delegate:  None` field to the examples in the `recursion.md` docs?

2024-05-24 16:26 UTC, phorkish commented
Yep, done. Sorry about missing that.

2024-05-24 16:37 UTC, raphjaph approved these changes
LGTM

2024-05-24 16:44 UTC, merged