Add fee_rate_percentile.fr_10th to blockinfo
ordinals/ord pull request #3753
Opened 2024-05-14 23:26 UTC by benbuschmann

2024-05-17 14:27 UTC, raphjaph commented
Why only the 10th percentile? We could consider allowing all of them. 

Just out of interest, what are you building with this?

2024-05-17 15:03 UTC, benbuschmann commented
> Why only the 10th percentile? We could consider allowing all of them.
> 
> Just out of interest, what are you building with this?

I am looking for the lowest fee that was included in a block and min_fee_rate seems unreliable. I will be using the low fee rate to trigger a dynamic inscription.  I can add all 5 percentiles later today if you think it's worth doing all at once.

2024-05-17 15:53 UTC, raphjaph commented
As part of the strict backwards compatibility requirements for recursive endpoints we can only add fields, never remove or change an existing one. So I think adding all of them into one field makes sense here.

2024-05-17 16:55 UTC, benbuschmann commented
@raphjaph ok I added feerate_percentiles, does this look correct to you?

2024-05-21 00:05 UTC, benbuschmann commented on docs/src/inscriptions/recursion.md
> +  "feerate_percentiles": [0, 0, 0, 0, 0],
just added a note

2024-05-22 22:14 UTC, raphjaph requested changes
Looks good, just a small nit

2024-05-22 22:14 UTC, raphjaph commented on docs/src/inscriptions/recursion.md
> +Note: `feerate_percentiles` are feerates at the 10th, 25th, 50th, 75th, and 90th percentile weight unit (in satoshis per virtual byte).
```suggestion
Note: `feerate_percentiles` are feerates at the 10th, 25th, 50th, 75th, and 90th percentile in sat/vB).
```

2024-05-23 16:40 UTC, raphjaph approved these changes
LGTM

2024-05-24 11:19 UTC, merged