Add sat ranges to output
ordinals/ord pull request #3817
Opened 2024-06-11 18:52 UTC by cryptoni9n

partially addresses #3792 by adding the sat ranges to the `ord wallet output` command.  My feeling is that the sat ranges are information about the outputs, so this is a good place for this information.  

Next, I'll add the --all flag  so that `ord wallet sats --all` will return all sat ranges, and `ord wallet sats` without a flag will continue to only show rare sats (as it does today).  

The description for the command says `List wallet satoshis` - but what do we want this output to look like?  Should it simply be a list of sat ranges with no reference to the outputs, or anything else?  Would something like the mock-up below be acceptable? or do we want to display more info?

> `ord wallet sats`
[1111111111111111-1111111111111112, 1111111111111113-1111111111111114, 1111111111111115-1111111111111116, 1111111111111117-1111111111111118, 1111111111111119-1111111111111120, 1111111111111121-1111111111111122]

2024-06-27 20:18 UTC, raphjaph requested changes
I've simplified the code a bit and added a test. @cryptoni9n could you also add in this PR the `--ranges` flag. So you only see that ranges when it is specified. Let me know if you have any other questions.

2024-06-27 21:59 UTC, cryptoni9n commented
> I've simplified the code a bit and added a test. @cryptoni9n could you also add in this PR the `--ranges` flag. So you only see that ranges when it is specified. Let me know if you have any other questions.

Thanks Raph, I appreciate your help with this.  I'm out on vacation for about the next 10 days.  Sorry for the crap timing but I'm not sure I'll be able to get to this or the updates needed for my other PR's before then.  Will be sure to tackle this and the snafu updates when I get back.

2024-06-27 22:59 UTC, raphjaph commented
No worries, have fun on your vacation!

2024-06-28 13:17 UTC, raphjaph approved these changes
Just added the flag quickly myself.

LGTM

2024-06-28 13:23 UTC, merged