added the --all flag on `ord wallet sats`
ordinals/ord pull request #3824
Opened 2024-06-18 14:28 UTC by cryptoni9n

return all sat ranges in wallet, in addition to
the rare sats the command normally returns.

2024-06-27 20:24 UTC, raphjaph requested changes
Looks good, just a couple nits and also still needs a test

2024-06-27 20:24 UTC, raphjaph commented on src/subcommand/wallet/sats.rs
> +        .map(|range| format!("{} - {}", range.0, range.1))
```suggestion
        .map(|range| format!("{}-{}", range.0, range.1))
```

2024-06-27 20:24 UTC, raphjaph commented on src/subcommand/wallet/sats.rs
> +    help = "Display list of all sat ranges in wallet and special sats."
```suggestion
    help = "Display list of all sat ranges in wallet"
```

2024-06-27 20:41 UTC, cryptoni9n commented on src/subcommand/wallet/sats.rs
> +use clap::Parser;
updated to remove redundant use statement

2024-06-28 14:45 UTC, raphjaph approved these changes
LGTM

2024-06-28 14:50 UTC, merged