adding sat name to inscription page
ordinals/ord pull request #3826
Opened 2024-06-20 19:18 UTC by cryptoni9n

fixes #3199 

I didn't add the degree, though.  Please let me know if that is still desired and if you think it should be in a separate PR or not.

2024-06-20 20:33 UTC, casey commented
I think degree is probably not worth it. I don't think anyone aside from me has ever even mentioned degree notation 😅 Otherwise this looks good to me. @raphjaph what do you think?

2024-06-27 21:06 UTC, raphjaph requested changes

2024-06-27 21:06 UTC, raphjaph commented on templates/inscription.html
> +  <dd>{{ sat.name() }}</dd>
I think it would be cool to also link to `/sat/{sat_name}`. So just add an href and then this can be merged :)

2024-06-27 23:09 UTC, raphjaph approved these changes
LGTM

2024-06-27 23:15 UTC, merged