Update pointer specification
ordinals/ord pull request #3861
Opened 2024-07-16 19:53 UTC by ansigroup

Add missing info for pointer description:
`If the pointer is greater than the amount of output, runestone is a cenotaph.`

2024-08-03 01:13 UTC, raphjaph requested changes
Thanks! Just a small change

2024-08-03 01:13 UTC, raphjaph commented on docs/src/runes/specification.md
> +If the pointer is greater than the amount of outputs, runestone is a cenotaph.
```suggestion
runes are transferred to the first non-`OP_RETURN` output. If the pointer is greater than the 
number of outputs, the runestone is a cenotaph.
```

2024-08-05 18:58 UTC, raphjaph approved these changes

2024-08-05 19:14 UTC, raphjaph commented
I'm unable to update the branch, I think you disabled allow edits by maintainers

2024-08-05 21:41 UTC, ansigroup commented
> I'm unable to update the branch, I think you disabled allow edits by maintainers

Interesting, I did not disable allow edits, and do not see this option here to enable it. But, It was saying that branch is already outdated and require new merge with master, what I just did.

2024-08-05 22:08 UTC, raphjaph commented
Ok cool, will merge now!

2024-08-05 22:37 UTC, ansigroup commented
Now I see it again out-of-date with the base branch... 

![image](https://github.com/user-attachments/assets/7ac5eecb-c690-4b4d-831b-91c7dc58a28d)

2024-08-05 23:44 UTC, merged