nl translation of the full Ordinals Manual
ordinals/ord pull request #3907
Opened 2024-08-23 12:19 UTC by Tibebtc

nl translation of the full Ordinals Manual

2024-08-27 12:23 UTC, Tibebtc commented
@raphjaph Did I submit the PO file in the correct way?

2024-08-28 15:29 UTC, raphjaph requested changes

2024-08-28 15:29 UTC, raphjaph commented on nl.po
> +"Last-Translator: Zerone @0xZerone <zerone495@gmail.com>\n"
Is this your email? 

If not either update or get rid of this line

2024-08-28 15:29 UTC, raphjaph commented on docs/po/nl.po
> +"POT-Creation-Date: 2024-06-29T00:05:48-05:00\n"
Maybe update these or delete if you don't want your email here

2024-08-28 15:41 UTC, raphjaph approved these changes
LGTM

2024-08-28 16:03 UTC, merged