Proxy recursive satoshi endpoint
ordinals/ord pull request #4022
Opened 2024-10-25 19:17 UTC by arik-so

WIP: Builds on #4204.

In case people find any use in #4021, this provides a draft implementation.

2025-01-29 20:10 UTC, raphjaph commented on src/subcommand/server.rs
> +      if path.starts_with("r/sat") && path.contains("/at/") {
i pushed something but no idea if it's better. A local regtest index proxying stuff should be able to also have a sat index

2025-01-29 22:44 UTC, raphjaph commented on src/subcommand/server.rs
> +      if matches!(
I agree it's hacky but I don't think we can use axum stuff inside here.

2025-02-14 02:38 UTC, casey requested changes
Couple of comments, otherwise LGTM.

2025-02-14 02:38 UTC, casey commented on src/subcommand/server.rs
> +        .route("/r/sat/{sat_number}/at/{index}", get(r::sat_at_index))
I think this should be moved back, so it's sorted.

2025-02-14 02:38 UTC, casey commented on src/subcommand/server.rs
> +        .route("/r/sat/{sat_number}/at/{index}", get(r::sat_at_index))
We try to keep these sorted, so `r/sat/{sat_number}/at/{index}/content` should be moved up.

2025-02-14 02:38 UTC, casey commented on src/subcommand/server.rs
> +        path.split('/').collect::<Vec<&str>>().as_slice(),
Let's do a regex match instead, this is pretty heinous.

2025-02-14 02:44 UTC, casey commented on src/subcommand/server.rs
> +        .route("/r/sat/{sat_number}/at/{index}", get(r::sat_at_index))
I always just do `:sort` in vim and use whatever order that uses.

2025-02-17 19:52 UTC, raphjaph approved these changes
LGTM! @casey you wanna have a look at it one more time as well?

2025-02-24 23:21 UTC, casey requested changes
Minor comment, just about reusing the regex.

2025-02-24 23:21 UTC, casey commented on src/subcommand/server.rs
> +      let regex = Regex::new(r"(?m)r\/sat\/\d+\/at\/-?\d+$").unwrap();
This regex should be compiled once and reused using `lazy_static`

2025-02-24 23:21 UTC, casey commented on src/subcommand/server.rs
> +        .route("/r/sat/{sat_number}/at/{index}", get(r::sat_at_index))
Ah, sorry, I wasn't looking at the whole diff and didn't see that proxiable_routes had been moved into a separate section.

2025-02-25 00:14 UTC, casey approved these changes
LGTM!

Made some small changes:

- Forward slashes don't need to be escaped in regexes. (They do in Vim, but that's because `/` is often used at the pattern delimiter.)
- I think multiline mode `(?m)` was unnecessary.
- I pass the path through without removing the leading forward slash, and instead remove it in the `proxy` function, since I think that's cleaner.

2025-02-25 00:22 UTC, merged