Add `/r/parents/:inscription_id/inscriptions` endpoint.
ordinals/ord pull request #4088
Opened 2024-11-20 02:10 UTC by gmart7t2

Analogous to #3771 but for parents instead of children.

2024-11-24 21:35 UTC, gmart7t2 commented
The examples in the docs for /r/children/.../inscription* have the full output, so I did the same here. 

Maybe it makes sense to shorten those examples, too?

2024-12-18 22:27 UTC, casey requested changes
Looks good! The errors in `parent_inscriptions_recursive` should be handled, see my comment. In general, errors from the index shouldn't be ignored. `unwraps` on `Option`s are okay though, when we expect the index to contain the inscription.

2024-12-18 22:27 UTC, casey commented on src/subcommand/server.rs
> +            .unwrap()
These errors should be handled. If the result type of a map is `Result<T>`, then you can collect into a `Result<Vec<T>>`, which will return an error if any of the results is `Result::Err`.

2024-12-18 22:27 UTC, casey commented on src/subcommand/server.rs
> +            .ok()
Same here, this error should be handled.

2025-02-14 02:39 UTC, casey commented
Can you rebase or merge master? This has some conflicts.

2025-02-15 15:54 UTC, cryptoni9n commented
> Can you rebase or merge master? This has some conflicts.

rebased and ready for review

2025-02-16 00:58 UTC, casey requested changes
Looks mostly good to me! See comments.

2025-02-16 00:58 UTC, casey commented on docs/src/inscriptions/recursion.md
>      },
Can you put these deletions into a follow up PR? The change here which combines a very large deletion with some additions makes this harder to review.

2025-02-16 00:58 UTC, casey commented on src/api.rs
> +pub struct RelativeInscriptionRecursive {
Should `ChildInscriptionRecursive` be deleted in favor of this struct?

2025-02-16 00:58 UTC, casey commented on src/subcommand/server/r.rs
> +pub async fn parent_inscriptions_recursive(
Since we now have a dedicated module for recursive andpoints, `_recursive` isn't needed anymore:

```suggestion
pub async fn parent_inscription(
```

2025-02-16 00:58 UTC, casey commented on src/subcommand/server/r.rs
> +pub async fn parent_inscriptions_recursive_paginated(
Since we now have a dedicated module for recursive andpoints, `_recursive` isn't needed anymore:

```suggestion
pub async fn parent_inscriptions_paginated(
```

2025-02-16 00:58 UTC, casey commented on src/subcommand/server/r.rs
> +          let entry = index
This code looks identical to that in `children_inscriptions_paginated`, you can define a function which contains the code which takes the index and goes from an inscription ID to a `api::RelativeInscriptionRecursive`, and call it in both places.

2025-02-16 22:23 UTC, cryptoni9n commented on docs/src/inscriptions/recursion.md
>      },
I've backed up the deletion commit to a local branch and rebased; will submit a separate PR for those changes.

2025-02-16 22:23 UTC, cryptoni9n commented on src/subcommand/server/r.rs
> +pub async fn parent_inscriptions_recursive(
updated

2025-02-16 22:24 UTC, cryptoni9n commented on src/subcommand/server/r.rs
> +pub async fn parent_inscriptions_recursive_paginated(
updated

2025-02-16 23:14 UTC, cryptoni9n commented on src/subcommand/server/r.rs
> +          let entry = index
added `fn to_relative_inscription` to reduce duplication

2025-02-16 23:41 UTC, cryptoni9n commented on src/api.rs
> +pub struct RelativeInscriptionRecursive {
I couldn't see any reason why not.  It's not being used anywhere else in the code as far as I can see.  I've taken it out in the latest commit.

2025-02-17 19:48 UTC, raphjaph approved these changes
LGTM

2025-02-17 19:49 UTC, merged